### ISSUE TITLE
Implement Kubernetes type detection mechanism

### ISSUE THREAD

**Issue by slashben** [armosec/kubescape#102]
Kubescape uses today pure K8s API to look for security issues.

The next step will be to look on data coming outside K8s API like:
* Etcd encryption configuration
* API server configuration
* CNI information

First step for Kubescape to find these information is to identify which kind of cluster it is scanning:
* Native Kubernetes
* EKS
* GKE
* AKS
* Openshift

We need to have a function returning the type of cluster, here is a prototype proposal:
```
func GetKubernetesType() K8sType
```

**Comment by dwertent** [comment]
@Daniel-GrunbergerCA  Did you implement this?

**Comment by Daniel-GrunbergerCA** [comment]
@dwertent Meanwhile for EKS and GKE

**Comment by dwertent** [comment]
@slashben Is this issue still relevant?

**Comment by slashben** [comment]
This can be closed, we can open another issue for AKS support
