### ISSUE TITLE
Implementing functionality that retrieves AKS configuration properties

### ISSUE THREAD

**Issue by slashben** [armosec/kubescape#105]
Kubescape uses today pure K8s API to look for security issues.

The next step will be to look on data coming outside K8s API like:
* Etcd encryption configuration
* API server configuration
* CNI information

Kubescape needs to be able to retrieve the description of a AKS cluster from Azure API to evaluate it.

https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/get#managedcluster

Need to implement a function returning this information for the cluster configured in the active context in ".kube/config"

**Comment by omkar342** [comment]
Hey I have no idea about kubernetes but I have thirst to learn & contribute to it. Would you like to help me with basic resources to solve this issue so that I can help you to contribute more?

**Comment by slashben** [comment]
hi @omkar342 , do you have some experience developing in Go? Working with AWS API?

**Comment by dwertent** [comment]
@Daniel-GrunbergerCA Did you implement this?

**Comment by Daniel-GrunbergerCA** [comment]
@dwertent  yes, it will be on the next release
