### ISSUE TITLE
binary not found issue.

### ISSUE THREAD

**Issue by teemosuny** [armosec/kubescape#113]
After dockerizing, I wanted to run kubescape in my application on a pod.
The image I used is alpine:3.13. However, when I run kubescape in the application, the output is as follows.

ash: kubescape: not found

I searched and found that it was due to a missing interpreter when building the binary([Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]). Considering this, can't we build a binary at the time of release?

**Comment by shifulbd** [comment]
[root@k8-build ~]# curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
Installing Kubescape...

######################################################################## 100.0%

Finished Installation.

**/bin/bash: line 53: kubescape: command not found** 
pls suggest to resolved this.
