### ISSUE TITLE
execute error issue.

### ISSUE THREAD

**Issue by teemosuny** [armosec/kubescape#114]
The following error occurred while running kubescape. 
I'm curious as to why the error occurred and how to fix it.
(I ran kubescape inside the pod after dockerizing.)

/ # kubescape scan framework nsa --use-default
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1616eed]

goroutine 1 [running]:
github.com/armosec/kubescape/cautils/k8sinterface.GetDefaultNamespace(0x1b8a1c0, 0xc00012b0b0)
        /home/runner/work/kubescape/kubescape/cautils/k8sinterface/k8sconfig.go:111 +0x8d
github.com/armosec/kubescape/cautils.NewClusterConfig(...)
        /home/runner/work/kubescape/kubescape/cautils/customerloader.go:72
github.com/armosec/kubescape/cmd.CliSetup(0x2ba9800, 0x3)
        /home/runner/work/kubescape/kubescape/cmd/framework.go:124 +0x607
github.com/armosec/kubescape/cmd.glob..func10(0x2b90ec0, 0xc0003119a0, 0x1, 0x2, 0x0, 0x0)
        /home/runner/work/kubescape/kubescape/cmd/framework.go:73 +0x1a5
github.com/spf13/cobra.(*Command).execute(0x2b90ec0, 0xc000311980, 0x2, 0x2, 0x2b90ec0, 0xc000311980)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x2b8ffc0, 0x0, 0x19a22a0, 0xc000046118)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/armosec/kubescape/cmd.Execute(...)
        /home/runner/work/kubescape/kubescape/cmd/root.go:16
main.main()
        /home/runner/work/kubescape/kubescape/main.go:12 +0x36

**Comment by dwertent** [comment]
@teemosuny Can you please share the version you are running? Run  `kubescape version`.
Thank you

**Comment by teemosuny** [comment]
latest version. v1.0.97

**Comment by dwertent** [comment]
@teemosuny  Thank you for sharing the issue. I pushed a fix that should be published next release.
