### ISSUE TITLE
Execution error on MacOS

### ISSUE THREAD

**Issue by smruti-21** [armosec/kubescape#12]
The following command is throwing error - 

`kubescape scan framework nsa --exclude-namespaces kube-system,kube-public`

ERROR: 
`-bash: /usr/local/bin/kubescape: cannot execute binary file: Exec format error`

**Comment by dwertent** [comment]
Do you still encounter the issue?

**Comment by BenHirschbergCa** [comment]
> Do you still encounter the issue?

Ple

**Comment by smruti-21** [comment]
It's working as expected with latest version. 
Thank you! 🙂

**Comment by BenHirschbergCa** [comment]
> It's working as expected with latest version.
> Thank you! 🙂

Great to hear it :)
