### ISSUE TITLE
Update documentation with explicit Go version which should be used

### ISSUE THREAD

**Issue by VladyslavKurmaz** [armosec/kubescape#18]

**Comment by mozai** [comment]
I think I ran into this today:  got `build kube-escape: cannot find module for path io/fs` and checking the documentation it seems iofs showed up in Golang version 1.16 .... but my distro still publishes Golang 1.12

**Comment by dwertent** [comment]
We added go version so you can find it in the [readme](https://github.com/armosec/kubescape#how-to-build)

@VladyslavKurmaz Please confirm so I will close the issue

**Comment by VladyslavKurmaz** [comment]
@dwertent thanks, this works for me!
...
BTW, if idea below makes sense for you, I can create corresponding PR.
...
I'm working on the next project - https://github.com/project-talan/tln-cli
In nutshell, talan helps to create predictive isolated development environment: whatever third-party components are required to build kubescape, it will be automatically managed by tln
> tln install --depends

Please check 3 min tutorial for more info in project's repository.

Plus, I can add kubescape into next talan release, so developers can very easy install any number of kubescape versions simultaneously.
This is an example from my dev box, different projects requires different version for kubectl
<img width="496" alt="Screenshot 2021-08-31 at 17 35 30" src="https://user-images.githubusercontent.com/1977961/131524262-56de2cac-1957-403e-8838-9595be14707f.png">

**Comment by dwertent** [comment]
@VladyslavKurmaz  This sounds interesting. We will follow up in email :)
