### ISSUE TITLE
Intermittent download issues

### ISSUE THREAD

**Issue by tim-sendible** [armosec/kubescape#193]
```
error: failed to download file, status code: 403 Forbidden
2021/10/25 13:13:31 failed to download file, status code: 403 Forbidden
2021/10/25 13:13:31 failed to download file, status code: 403 Forbidden
ARMO security scanner starting
[progress] Downloading/Loading policy definitions
kind: Framework, name: nsa, error: control 'nsa' not found
```

This is the v1.0.126 container running in eks 1.21. Running the command `kubescape scan framework nsa`

If I wait an hour or two, one run will be successful, and then subsequent runs will fail again.

**Comment by dwertent** [comment]
Kubescape downloads the release and does no longer use `api.github` so this is fixed :)
