### ISSUE TITLE
allow disabling latest check when running

### ISSUE THREAD

**Issue by 06kellyjac** [armosec/kubescape#200]
We build kubescape in a sandbox that doesn't have network access.

Luckily the below is just a warning so we are able to generate the completions but the error messages are still quite scary for the average observer/reviewer

```
error: failed to get latest releases from 'https://api.github.com/repos/armosec/kubescape/releases/latest', reason: Get "https://api.github.com/repos/armosec/kubescape/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:41292->[::1]:53: read: connection refused
error: failed to get latest releases from 'https://api.github.com/repos/armosec/kubescape/releases/latest', reason: Get "https://api.github.com/repos/armosec/kubescape/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:50270->[::1]:53: read: connection refused
error: failed to get latest releases from 'https://api.github.com/repos/armosec/kubescape/releases/latest', reason: Get "https://api.github.com/repos/armosec/kubescape/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:58837->[::1]:53: read: connection refused
```

Either a flag or an environment variable or both would be nice

See: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/infracost/default.nix#L35

---

It might also be worth caching the result so it's not checked every single command but that can be a separate issue

**Comment by dwertent** [comment]
@06kellyjac  Add `export KUBESCAPE_SKIP_UPDATE_CHECK=true`.

Good luck :)

**Comment by 06kellyjac** [comment]
Thanks
