### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by jasbroek** [armosec/kubescape#209]
When using the tool on a larger cluster (~50 nodes, ~1300 pods), it crashes on using too much ram.
At least 8GB is needed to successfully run the tool with the following scan:  
`kubescape scan framework nsa --exclude-namespaces kube-system,kube-public -o kubescan.out`

I'm currently not able to look at the code and investigate where this high memory usage comes from.
Just wanted to give this feedback for active maintainers of the project.

**Comment by dwertent** [comment]
Thank you @jasbroek for your feedback.
Kubescape loads all the workloads in it's memory for efficiency reasons. This can explain the high memory usage when scanning very big clusters.

I do not have a perfect solution for you, but if you wish you can exclude the different namespaces.
e.g. you are running namespaces a,b,c,d :
1. exclude namespaces `a`,`b` -> `kubescape scan framework nsa --exclude-namespaces kube-system,kube-public,a,b`
2. exclude namespaces `c`,`d` -> `kubescape scan framework nsa --exclude-namespaces kube-system,kube-public,c,d`.

This should reduce the number of scanned Kubernetes objects.
