### ISSUE TITLE
Allow option to only scan a single namespace

### ISSUE THREAD

**Issue by L1ghtman2k** [armosec/kubescape#212]
In our company, we want namespace owners to handle vulnerabilities that show up on their respective namespaces. Is it possible to configure kubescape to only scan a specific set of namespaces, and if not, could this be turned into a feature request? 

I assume there are probably ways to hack around this by getting all namespaces, and feeding them into `exclude-namespaces` list, or doing a regex, but I am not sure if there are any performance implications there (for instance, kubescape might try to fetch resources it doesn't really need to scan because they should be excluded), it would be nice to have a dedicated white-list approach for scanning namespaces like:

```
kubescape scan framework nsa --scan-namespaces namespace_to_scan-2,namespace_to_scan-1 --format json --output results.json
```
where kubescape only fetches the manifest files from specified namespaces

**Comment by dwertent** [comment]
@L1ghtman2k  Thank you for your feedback.

@rotemamsa We can add an `--include-namespaces` as following:
```
kubescape scan framework nsa --include-namespaces namespace_to_scan-2,namespace_to_scan-1 --format json --output results.json
```

This solution will also be is a nice workaround for issue #209 .

**Comment by L1ghtman2k** [comment]
That was fast 😂, thanks a lot!

**Comment by dwertent** [comment]
@L1ghtman2k  Sure 😎.

Notice I delivered my update to the pipe, this feature should be next release :)
