### ISSUE TITLE
Docker container always complains "You are not updated to the latest release"

### ISSUE THREAD

**Issue by mboersma** [armosec/kubescape#215]
```shell
% docker run quay.io/armosec/kubescape:v1.0.128 version
Warning: You are not updated to the latest release: v1.0.128
Your current version is: None
```

I saw the same warnings from the `:v1.0.126` quay.io container before, when that was the latest release.

All `kubescape` commands emit this warning before doing anything else, so it would be useful if the new version check could be fixed and/or made optional through a command-line argument (as in #200).

*Edit*: Sorry, somehow I missed #207, which should fix this.

**Comment by dwertent** [comment]
@mboersma Fixed :)

```
david@david-VirtualBox:~$ docker run quay.io/armosec/kubescape:v1.0.131 version
Your current version is: v1.0.131
```
