### ISSUE TITLE
Use the tool offline

### ISSUE THREAD

**Issue by ohadm2** [armosec/kubescape#22]
Hi.

I noticed that the tool requires downloading extra files to work.

Can I somehow download them offline and make them accessible to the tool?

I want to run it in an environment without internet access.

Regards,

**Comment by sachua** [comment]
What I did was to copy the text from the Framework sources into a .txt file and reference that in the OPAFRAMEWORKGet function in handlepullpolicies.go 

Sources can be found here:

NSA: https://dashbe.eudev3.cyberarmorsoft.com/v1/armoFrameworks?customerGUID=11111111-1111-1111-1111-111111111111&frameworkName=NSA&getRules=true

MITRE: https://dashbe.eudev3.cyberarmorsoft.com/v1/armoFrameworks?customerGUID=11111111-1111-1111-1111-111111111111&frameworkName=MITRE&getRules=true

**Comment by dwertent** [comment]
@ohadm2 Thank you for your feedback, this feature is in our roadmap.
In the meantime, I recommend you use the workaround @sachua suggested.

**Comment by ohadm2** [comment]
That's great!

Thanks a lot for the info and the very fast feedback! 

:)

**Comment by dwertent** [comment]
@ohadm2, @sachua We finally [support offline scanning](https://github.com/armosec/kubescape/blob/master/README.md#offline-support)

Enjoy 😅

**Comment by ohadm2** [comment]
Thanks! :)
