### ISSUE TITLE
RBAC Manager markes as failed for control: Exec into container

### ISSUE THREAD

**Issue by lyssar** [armosec/kubescape#224]
# Issue

When you run kubescape scan framework nsa on a cluster running rbac-manager kubescape will list this issue

```
[control: Exec into container] failed 😥
Description: Attackers with relevant permissions can run malicious commands in the context of legitimate containers in the cluster using “kubectl exec” command. This control determines which subjects have permissions to use this command.
      ClusterRole - cluster-admin
      ClusterRoleBinding - cluster-admin
      ClusterRole - rbac-manager-1636550927
      ClusterRoleBinding - rbac-manager-1636550927
Summary - Passed:137   Warning:0   Failed:2   Total:139
Remediation: It is recommended to prohibit “kubectl exec” command in production environments. It is also recommended not to use subjects with this permission for daily cluster operations.
```

But actually rbac doesn't have access to exec anything. So I think this is a false positive.

# To reproduce

- Install a cluster locally with k3d for example
- Apply rbac manager via helm (https://rbac-manager.docs.fairwinds.com/introduction/#getting-started)
- run `kubescape scan framework nsa`
- I tried `kubectl auth can-i`, `k9s popeye` and `kubectl who-can` to verify.

For me this looks like a false positive report because rbac-manager cant run any. If this is intended please explain why and how can I check this by hand (or what do you check).

Kind regards

**Comment by dwertent** [comment]
Thank you @lyssar, we are investigating this issue you opened.
I hope it's ok that we will reach out to you if we have further questions 😅

**Comment by leonidsandler** [comment]
Thank you @lyssar for your report. The issue is related to a proper verification of the API group. We will make the fix ASAP.

**Comment by Daniel-GrunbergerCA** [comment]
Thank you @lyssar  for pointing out this issue. We fixed it on the latest version of the nsa framework.
