### ISSUE TITLE
Cannot exclude "Allow privilege escalation" check

### ISSUE THREAD

**Issue by echoblag** [armosec/kubescape#228]
Whenever I try to exclude the Allow privilege escalation check it always fails.

I have tried and tested this across multiple recent releases, on its own, with other exceptions, and any possible derivatives. I did check for similar issues and found some useful information that got me this far.

I have been able to successfully disable other checks like:
- `immutable-container-filesystem`
- `linux-hardening`

``` json
"posturePolicies": [
      {
        "frameworkName": "NSA",
        "ruleName": "allow-privilege-escalation"
      }
    ]
```

**Comment by echoblag** [comment]
As with any of the other exceptions the goal here is to focus Kubescape on the desired deployments and namespaces. I have tried to work around this to some degree, but have hit a limit on how far I can go with the exceptions json approach.

**Comment by echoblag** [comment]
Hopefully this something that can be sorted out with documentation. I am relying on lowercasing and hyphenating checks based on a few exception example I have found.

I'm starting to run into other exclusions that behave the same way.

**Comment by dwertent** [comment]
Hi @echoblag I will tests this.
1. Can you please share your full exceptions file? Tnx
2. We will add documentation regarding the exceptions :)

**Comment by dwertent** [comment]
@echoblag Notice the rule name is  ["rule-allow-privilege-escalation"](https://github.com/armosec/regolibrary/blob/master/rules/rule-allow-privilege-escalation/rule.metadata.json#L2)

Your exceptions file should look as following:
```
[
    {
        "name": "exclude-nginx-in-minikube",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
            {
                "designatorType": "Attributes",
                "attributes": {
                    "kind": ".*"
                }
            }
        ],
        "posturePolicies": [
            {
                "frameworkName": "NSA",
                "ruleName": "rule-allow-privilege-escalation"
            }
        ]
    }
]
```

I added a basic documentation and some examples you can find [here](https://github.com/armosec/kubescape/tree/dev/examples/exceptions#kubescape-exceptions) .

I hope this will help you 😄

**Comment by echoblag** [comment]
Thank you, that totally did the trick!
