### ISSUE TITLE
Scanning form stdin is broken

### ISSUE THREAD

**Issue by dblbirdie** [armosec/kubescape#233]
It seems that scanning from stdin is broken in the current version. The file test.yaml is a valid Kubernetes manifest (e.g., [this example](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)).

```console
$ kubescape version
Your current version is: v1.0.131

$ kubescape scan framework nsa test.yaml --keep-local
... # This scan is performed as expected.

$ cat test.yaml | kubescape scan framework nsa - --keep-local
ARMO security scanner starting
[progress] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
empty list of workloads - no workloads found
```

Expected result: Same output. No errors.

**Comment by dwertent** [comment]
@dblbirdie Thank you for pointing it out.
Will be fixed ASAP

**Comment by dwertent** [comment]
@dblbirdie Fixed has been released :)

**Comment by dblbirdie** [comment]
@dwertent Thanks for looking into it. I can confirm that everything works again. 👍
