### ISSUE TITLE
Scan NSA Framework Exposed Dashboard Passes on v2.0.0 when expecting Fail

### ISSUE THREAD

**Issue by agentpoyo** [armosec/kubescape#236]
When scanning  the NSA FRAMEWORK against a cluster, I've purposely installed dashboard v2.0.0 to do some tests for the [cnf-testsuite](https://github.com/cncf/cnf-testsuite) and it's passing; expectations are it should be failing based on the container image version detected.

Container Version for kubernetes-dashboard:
```
root@master1:~/cnf-testsuite/tools/kubescape# kubectl get pods -n kubernetes-dashboard -o jsonpath="{.items[*].spec.containers[*].image}" |tr -s '[[:space:]]' '\n' |sort |uniq -c
      1 kubernetesui/dashboard:v2.0.0
      1 kubernetesui/metrics-scraper:v1.0.4
```

Method to install the dashboard:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
```

Here is the test results from kubescape:
```
./kubescape scan framework nsa

... snipped output ...

[control: Exposed dashboard] passed 👍
Description: Kubernetes dashboard versions before v2.0.1 do not support user authentication. If exposed externally, it will allow unauthenticated remote management of the cluster. This control checks presence of the kubernetes-dashboard deployment and its version number.
Summary - Passed:9   Excluded:0   Failed:0   Total:9
```

Screenshot:
![exposed_dashboard](https://user-images.githubusercontent.com/14348948/142266888-b07583b6-c1ef-42f3-aca7-d198844ec6e4.png)

**Comment by dwertent** [comment]
@agentpoyo Thank you for notifying us about this issue.
We will look in to it :)

**Comment by leonidsandler** [comment]
Hi @agentpoyo, while we are checking this issue, can you please confirm that your dashboard is exposed via either "NodePort" or "LoadBalancer" service type?

**Comment by agentpoyo** [comment]
> Hi @agentpoyo, while we are checking this issue, can you please confirm that your dashboard is exposed via either "NodePort" or "LoadBalancer" service type?

Let me check as I was doing the basic install of the dashboard based on the k8 docs and running it via kubectl proxy command I believe.

**Comment by agentpoyo** [comment]
So by default they used ClusterIP but once I changed to NodePort, I could get this to error in our cnf-testsuite.
![exposed_dashboard_error](https://user-images.githubusercontent.com/14348948/142453789-598253ae-4466-40ef-b895-a2c69cabd04e.png)

**Comment by agentpoyo** [comment]
Having a deeper understanding of security myself, a majority of the attacks on systems are actually compromised within the company, organization and network. I think it makes sense to alert or fail this version on all levels if an attacker can gain unprivileged access to the systems. My two cents. :+1:

**Comment by leonidsandler** [comment]
Hi @agentpoyo, this is really good point. Clearly external exposure is way more dangerous than internal, but both are indeed important. NSA was specifically talking about the external exposure danger, so we took it "literally". We now have another framework called ARMO Best. It is our own framework where we can broaden the boundaries without breaking backward compatibility. Stay tuned, we will make a final decision soon.

**Comment by dwertent** [comment]
Closing since this control is following the NSA guidelines [as explained](https://armoui.eustage2.cyberarmorsoft.com/)
