### ISSUE TITLE
Support standard CI test report formats

### ISSUE THREAD

**Issue by lee-b** [armosec/kubescape#237]
Please support common report output formats, like xUnit.  Currently, outputting to a file results in an ANSI dump of what would normally be output to the console.  Machine-readable formats are needed.

**Comment by lee-b** [comment]
Never mind; found the output format config option.  Would suggest defaulting to one of the non-prettyprinter options when outputting to a file.

**Comment by dwertent** [comment]
@lee-b  Thanks for your suggestion. 
Since there are 4 different output formats, we prefer keeping the default format the same and let the user specify the preferred format when saving to a file :)
