### ISSUE TITLE
output json file too large

### ISSUE THREAD

**Issue by judexzhu** [armosec/kubescape#238]
Hi, I used the json file output and found it is too large, over 2GB a single file one cluster 

![image](https://user-images.githubusercontent.com/17834225/142700885-9c35451b-d9c0-47f6-917d-cdf8a8c6f48f.png)

is there any possibility to exclude the Kubernetes resource metadata into the output json?

Also, it's too large to submit to SAAS too, around 3600 objects

![image](https://user-images.githubusercontent.com/17834225/142701342-13f37056-93f9-4a04-961f-3c3e207a123e.png)

**Comment by dwertent** [comment]
@judexzhu Thank you for sharing.
1. We are working on sending the data using pagination, this should solve the submit issue.
2. I agree with you, the json file is to large. I'm thinking of a way of decreasing the size without breaking backward compatibility, do you have any suggestion? 

For now, you can swap the [call to print](https://github.com/armosec/kubescape/blob/master/resultshandling/results.go#L30) and the [call to submit](https://github.com/armosec/kubescape/blob/master/resultshandling/results.go#L32) (The data is removed before submitting so the output json will be less than 2G)

**Comment by judexzhu** [comment]
@dwertent Thanks for your help. I'm not a developer, so if I misunderstand something please forgive me. 

> For now, you can swap the [call to print](https://github.com/armosec/kubescape/blob/master/resultshandling/results.go#L30) and the [call to submit](https://github.com/armosec/kubescape/blob/master/resultshandling/results.go#L32) (The data is removed before submitting so the output json will be less than 2G)

I tried to swap the line 30  with line 32-34,(go build and run again) but the output file size looks like the same 

but if I replace `resultsHandler.printerObj.ActionPrint(opaSessionObj)`  with `resultsHandler.reporterObj.ActionSendReport(opaSessionObj)`, the output file is just empty. Sorry if I didn't get it right

> I agree with you, the json file is to large. I'm thinking of a way of decreasing the size without breaking backward compatibility, do you have any suggestion?

for this one, I was think about to add a flag to let user choose for  a detail report file  or a brief report file. The detail report is like right now, it has everything, including the k8sapiobject metadata, the brief report (short one), it only including the the score and the failed object name, namespace and kind

like me, my goal is to show a score card which result from the kubescape to let our developer knows how they are doing with their current deployment, for we use namespaces to separate the teams and the workload , they basically not care about the whole cluster but only about their own namespaces, so give a score to each namespace or each deployment might much more useful than a overall cluster report, and also give us a clear view to know which namespace (which team or which product )we need to focus on first.

it's just  my 2 cents. 😄

**Comment by SmartGuyy** [comment]
Hello @rotemamsa, i just had the same issue when doing a Kubescape scan with latest version (only for MITRE scan), it also happens when doing scan with your helm chart : 

HTTP-ERROR: '413 Request Entity Too Large', BODY: '<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
', HTTP-HEADERS: map[Content-Length:[183] Content-Type:[text/html] Date:[Mon, 13 Dec 2021 11:55:20 GMT] Server:[nginx/1.17.8] Strict-Transport-Security:[max-age=15724800; includeSubDomains]], HTTP-BODY-BUFFER-LENGTH: 183:

**Comment by dwertent** [comment]
Reopening this issue since we did not complete the report pagination

**Comment by rotemamsa** [comment]
hi there @SmartGuyy  , we just released new kubescape version with pagination support, 
please, check that out with this issue- and update the results.

**Comment by dwertent** [comment]
Fixed
