### ISSUE TITLE
rules?

### ISSUE THREAD

**Issue by zetaab** [armosec/kubescape#24]
its quite difficult to debug what is wrong because the actual rules are not visible anywhere?

for instance I have failing rule "Automatic mapping of service account" but automountServiceAccountToken: false at least does not solve that.

Then "Linux hardening" I assume that this is something related like selinux or similar? But it would be nice to have somekind of documentation how to solve these "tests" or then publish the actual tests as well.

**Comment by BenHirschbergCa** [comment]
Hi! We are working on publishing the OPA rules we are using, they will be published very soon.

The "Automatic mapping of service account" checks the serviceaccount object for the automountServiceAccountToken , can you confirm that this is your case? (or you define it at the Pod level?)

**Comment by dwertent** [comment]
@zetaab We [published the actual tests](https://github.com/armosec/regolibrary). Please feel free to comment and contribute 😅
