### ISSUE TITLE
Incorrect stats in the results Summary table

### ISSUE THREAD

**Issue by extensure123** [armosec/kubescape#246]
The earlier versions of kubescape displayed the number of controls (21) and correct resource count sum for failed resources, all resources. However, the latest version I installed v1.0.132 is NOT displaying the number of controls (now 22) and the correct sum of failed resources (8) and all resources (16) that gives a misleading %success figure. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/94514187/144360466-648980b1-4d2b-4852-aed0-09939a85c26c.png)

**Comment by dwertent** [comment]
@extensure123 The previous versions counted the resources using a simple sum function so the summery counter was not a unique resource count. 
e.g. If the same Deployment failed in three controls, the summery will counter was three although only one resource failed.
In the new versions, kubescape uses an unique resource count this way the summery is more accurate. 

We are working on a better score mechanism that does not only count the resources but also take in account the severity and other important parameters. Stay tuned :)

**Comment by vishalgoyal16444** [comment]
@dwertent : Thanks for clarifying. If you see the screen shot which we attached, it says 8 for FAILED RESOURCES. In the table, we can see 5 different policies failed for these 8 resources always. In this case showing a total of 8 does not really help - right ?

**Comment by dwertent** [comment]
@vishalgoyal16444 Right, the summary can be ether 8 or 40 (5*8), but because the number that is displayed is a counter of resources, we think it's better counting a resource once and not multiple times. 
Also, if you fixed the resource in one of the controls, but the rest of the controls are still failing, the number of failed resources remain the same since those resources are still failing.

As I mentioned, this may be a bit confusing because the numbers in the summary table don't add up, we will release very soon a more sophisticated score mechanism and not simple counters.

If you wish, I can share with you more details regarding the developing risk-score mechanism :)

**Comment by vishalgoyal16444** [comment]
Thanks @dwertent for sharing the thoughts. This helps. We have been keenly looking at leveraging Kubescape and glad to see this being actively developed and enhanced. Will wait for next updated version. If you are fine, please do share more details regarding the developing risk-score mechanism.

**Comment by extensure123** [comment]
Thanks @dwertent. Yes, it will be helpful to get more details regarding the risk-score mechanism.
"_Also, if you fixed the resource in one of the controls, but the rest of the controls are still failing, the number of failed resources remain the same_" - so effectively the % Success needle will not move in my next analysis run even if I may have fixed a few controls (not all) against that resource. I hope that's a correct interpretation :)

**Comment by dwertent** [comment]
> so effectively the % Success needle will not move in my next analysis run even if I may have fixed a few controls (not all) against that resource. I hope that's a correct interpretation :)

Correct.

**Comment by leonidsandler** [comment]
Hi, this algorithm is still being developed. It will show you a risk score in which we take a percentage of failed controls out of the possible worst case. For example, if you have only one control checking for privileged PODs and one out of ten PODs is failed, your risk score will be 10; if two failed, the risk score will be 20. It is relatively easy to explain on single control example, but when we deal with many controls applied to different types of resources it gets more complicated. We are fine-tuning it now and will most likely have valuable feedback after we release it and will have to improve.
