### ISSUE TITLE
include-namespaces shows nothing if more than a single namespace is passed.

### ISSUE THREAD

**Issue by annerajb** [armosec/kubescape#247]
## Info

* Software Version  v1.0.132
* Platform Linux ubuntu

## Summary 
It seems the ability to select a single namespace broke the ability to choose more than 1.

### Failure runs 
`kubescape scan framework nsa --include-namespaces 'ns-a,ns-b,ns-c'`

`kubescape scan framework nsa --include-namespaces 'ns-a,'` (left comma on purpose at the end to make it run the split logic)
Will present only cluster level (Bindings and roles) findings / resources. 

### Succesfull runs
it works succesfully on the following scenarios:

if you run `kubescape scan framework nsa --include-namespaces 'ns-a,ns-a'` (repeated on purpose it finds findings at the pods / deployment levels.
same results if you run `kubescape scan framework nsa --include-namespaces 'ns-a'` 

This code was recently changed here https://github.com/armosec/kubescape/issues/212

Which may have introduced the issue.

**Comment by dwertent** [comment]
@annerajb  Thank you for pointing out this issue. I pushed the fix, it will be available next release :)

**Comment by dwertent** [comment]
@annerajb  The fixed has been released.
Please let us know if you encounter any other issue :)
