### ISSUE TITLE
validate Helm Charts

### ISSUE THREAD

**Issue by developer-guy** [armosec/kubescape#259]
IDK, there is active support to do, but it'd be nice to validate Helm Charts by using kubescape. AFAIK, kubescape can validate manifest files, so to make it compliant with validating Helm Charts would be very easy because once we run the `helm template,` then we have all the manifests managed through Helm Chart, then pass those to the kubescape to validate.

cc: @dentrax

**Comment by developer-guy** [comment]
feel free to assign it to use if you agree with the idea 🙋🏻‍♂️

**Comment by dwertent** [comment]
@developer-guy I'm not sure I understood you correctly, do you mean scanning the generated templates? If so, I added [here](https://github.com/armosec/kubescape#scan-helm-charts---render-the-helm-chart-using-helm-template-and-pass-to-stdout) an example

**Comment by developer-guy** [comment]
nice @dwertent! The thing is lets break down this logic into kubescape directly without requiring to run `helm template` first, for example, accept a Chart path, and do the same under the hood, makes sense?

**Comment by dwertent** [comment]
@developer-guy Why is it necassery? Is there a reason you want kubescape to render the template?

I'll explain my concerns and please feel free to share your thoughts -
1. If you have an issue rendering the helm template (wrong version/spelling issues or any other reason) it is not the responsibility of Kubescape to handle the error, you might not understand why it's not working
2. There are flags and other parameters you can use when rendering a helm template, I don't see why Kubescape should know and support all types of helm inputs

We want Kubescape to integrate with as many platforms and technologies as possible - the more the better and we invite anyone who wants to contribute to do so. But we need to make sure we effect the usability and simplicity of the tool as less as possible.

What are your thoughts?

**Comment by dwertent** [comment]
Closed since I did not receive any response
