### ISSUE TITLE
Unable to submit report for local YAML file

### ISSUE THREAD

**Issue by magikid** [armosec/kubescape#265]
# What happened

I was trying to scan my k8s yaml file using the following command.
```
$ kubescape scan framework nsa --submit --account=foobar docker/kubernetes/build/staging.yaml
```

The command runs and I see results but at the end, errors out giving the following error message:
```
https://report.armo.cloud/k8s/postureReport?clusterName=&customerGUID=foobar&reportID=baz, HTTP request failed. URL: '/k8s/postureReport?clusterName=&customerGUID=foobar&reportID=baz', HTTP-ERROR: '400 Bad Request', BODY: 'missing cluster name', HTTP-HEADERS: map[Content-Length:[20] Content-Type:[text/plain; charset=utf-8] Date:[Mon, 13 Dec 2021 19:39:06 GMT] Server:[nginx/1.17.8] Strict-Transport-Security:[max-age=15724800; includeSubDomains]], HTTP-BODY-BUFFER-LENGTH: 20:
```

I'm not really sure what to do about this as I see no place for me to set the cluster's name.  Curiously, saving the results to a JSON file and then submitting that works just fine.

```
$ kubescape scan framework nsa --account=foobar docker/kubernetes/build/staging.yaml --format json --output results.json

ARMO security scanner starting
[progress] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[success] Let’s start!!!
[progress] Scanning cluster 
◑ [success] Done scanning cluster 

Final score: 2
$ kubescape submit results results.json 

Data has been submitted successfully
```

**Comment by dwertent** [comment]
@magikid You are right, the submitting features where designed for submitting cluster results and not for submitting yaml files results, I think the main reason is because the SaaS version displays the results per cluster and when you scan yamls the SaaS version will not display the results so there is no purpose of submitting them.

When you ran `$ kubescape submit results results.json` did you have a cluster running in the same environment? If so, you will find your submitted results under that cluster - which is wrong. If you did not have a cluster, I will investigate why was the data submitted.

**Comment by slashben** [comment]
hi @magikid , as @dwertent  said, we are not yet supporting it. It is in our roadmap :)
we are going to start doing roadmap meeting where we do feature design discussions, I'd love to have your input on this there. Would you like me to send an invite?

**Comment by magikid** [comment]
@dwertent No, I didn't have a cluster running in the same environment.

@slashben Thank you for the offer but no thanks.  One of my co-workers mentioned this tool so I was just taking it out for a spin.

**Comment by vishalgoyal16444** [comment]
> hi @magikid , as @dwertent said, we are not yet supporting it. It is in our roadmap :) we are going to start doing roadmap meeting where we do feature design discussions, I'd love to have your input on this there. Would you like me to send an invite?

We want the same feature. To be able to see YAML file scan results on SaaS platform.

**Comment by slashben** [comment]
> > hi @magikid , as @dwertent said, we are not yet supporting it. It is in our roadmap :) we are going to start doing roadmap meeting where we do feature design discussions, I'd love to have your input on this there. Would you like me to send an invite?
> 
> We want the same feature. To be able to see YAML file scan results on SaaS platform.

@vishalgoyal16444 , we are in design phase. Would you be ready for 1 on 1 discussion to check if our proposed SaaS solution makes sense to you?

**Comment by vishalgoyal16444** [comment]
@slashben : We had a call with Amir from your team yesterday and discussed what we are doing and discussed this point as well on YAML. It was great to know from Amir on new things coming up and we look forward to it.

Have started exploring SaaS platform recently and will check the same in detail.
