### ISSUE TITLE
400 bad request missing clusterName

### ISSUE THREAD

**Issue by ThijsBorst** [armosec/kubescape#273]
I'm using the helm install for Kubescape and when this runs, I'm getting the following error:

`https://report.armo.cloud/k8s/postureReport?clusterName=&customerGUID=xxxxxx&reportID=xxxxx, HTTP request failed. URL: '/k8s/postureReport?clusterName=&customerGUID=xxxxxx&reportID=xxxxxx', HTTP-ERROR: '400 Bad Request', BODY: 'missing cluster name', HTTP-HEADERS: map[Content-Length:[20] Content-Type:[text/plain; charset=utf-8] Date:[Thu, 16 Dec 2021 13:41:13 GMT] Server:[nginx/1.17.8] Strict-Transport-Security:[max-age=15724800; includeSubDomains]], HTTP-BODY-BUFFER-LENGTH: 20:
`

Configmap has the correct value "clusterName": "myclustername"

**Comment by dwertent** [comment]
Thank you @ThijsBorst. Can you please share the command you ran so I can investigate?

**Comment by ThijsBorst** [comment]
Hi @dwertent ,

I just ran the helm script:

`helm --debug upgrade --install armo armo/armo-cluster-components -n armo-system --create-namespace --set accountGuid=[ACCOUNT_ID] --set clusterName=[CLUSTERNAME]`

Then after in the scanner job the error shows at the bottom in the logs. It doesn't show the command it tries to run. It just shows the error above...

**Comment by dwertent** [comment]
@ThijsBorst Thank you. I will reproduce and fix :)

**Comment by slashben** [comment]
@ThijsBorst , we cannot reproduce this by ourselves. Can it be that your actual cluster name contains special characters?

in any case, we can hop on a 10m call with you for debugging this if you are ok with it

**Comment by ThijsBorst** [comment]
Well, I'm on holiday from tomorrow. So that will have to wait, but I've got two instances with the same problem now.

**Comment by slashben** [comment]
> Well, I'm on holiday from tomorrow. So that will have to wait, but I've got two instances with the same problem now. My colleague might contact you during my absence...

Sure, happy holydays!
