### ISSUE TITLE
Resources in table are not properly counted

### ISSUE THREAD

**Issue by marioosh11** [armosec/kubescape#276]
When we do a scan we see that kubescape counts wrong scaned resources.
Based on attached screen example:
EXCLUDED RESOURCES are counted as 1 but should be 3
ALL RESURCES are counted as 2 but should be 24
![ResultTable](https://user-images.githubusercontent.com/19182661/146897510-9c9fd5a8-7558-45bd-8207-6b2f53f08e5f.jpg)

**Comment by dwertent** [comment]
@marioosh11 The number of resources you see in the resource summary (last row) is the number of UNIQUE resources. This means, if you scanned a single resource and that resource failed in all of the controls so each control will report that resource has failed but in the resource summary there was only a single resource scanned there for only one resource can fail.

This might be confusing as you can see the discussion we had here -> #246

**Comment by marioosh11** [comment]
Ok thanks for explanation.
