### ISSUE TITLE
Get rid of `latest` tag in all versions

### ISSUE THREAD

**Issue by Moskovych** [armosec/kubescape#281]
All packages in the github releases: https://github.com/armosec/kubescape/releases contains `-latest`.

doesn`t matter which version you are downloading, it is always latest.....a bit confusing, isn't it?

**Comment by dwertent** [comment]
@Moskovych You are correct. Thank you :)

**Comment by dwertent** [comment]
Hi @Moskovych , I understand this might be confusing but we do not want to break backward compatibility. So for now we wont change the name of the release file
