### ISSUE TITLE
Export to pdf

### ISSUE THREAD

**Issue by mario-ezquerro** [armosec/kubescape#282]

**Comment by mario-ezquerro** [comment]
Export to pdf

**Comment by dwertent** [comment]
Thank you @mario-ezquerro for the feature recommendation. However, this is not in our road-map therefor will probably take a while until we get to it, but if you wish to take matters in your own hands and contribute you are more than welcomed!

Please let me know if so and I will be more than happy to show you exactly where you can integrate the PFD support :)

**Comment by mario-ezquerro** [comment]
Uhps! no PFD it is  PDF, export the state to PDF, sorry

**Comment by dwertent** [comment]
Yes, I was assuming you meant PDF... 😅

**Comment by slashben** [comment]
@mario-ezquerro , what would you like to see in a PDF report?

**Comment by mario-ezquerro** [comment]
It would be nice to use in audits, if you first have a summary of the problems ordered by priority, and then find it in detail.
What if instead of PDF it is in MD, and then everyone who exports it as they want? What do you think, what can be more useful ..

**Comment by slashben** [comment]
@mario-ezquerro , MD makes life much more easy for Kubescape , I will take is as a feature request

**Comment by alegrey91** [comment]
> Please let me know if so and I will be more than happy to show you exactly where you can integrate the PFD support :)

Hi @dwertent, @slashben, I would be interested to know how to integrate the PDF or MD support. If I can, I'll try to do this.

**Comment by slashben** [comment]
@alegrey91 , sounds great! 

Please be in touch with @dwertent so he can help you with the ramp up!

**Comment by alegrey91** [comment]
@dwertent let me know how you would like to integrate this functionality.

**Comment by alegrey91** [comment]
@dwertent what do you think to add a flag like `--export` where available options are `pdf` and `md`.

**Comment by dwertent** [comment]
@alegrey91 I think we should use the `--format` flag so it will look as following: `--format pdf --output results.pdf`/`--format md --output results.md`
I think this is a great suggestion and you are more than welcome to contribute this feature 😄

If you wish we can setup a session and discuss how and where. In short, you can add [here](https://github.com/armosec/kubescape/tree/dev/resultshandling/printer/v2) a file named pdf, with a struct that is compatible with the [IPrinter interface](https://github.com/armosec/kubescape/blob/dev/resultshandling/printer/printresults.go#L20)

**Comment by alegrey91** [comment]
Thanks, @dwertent. I'll take a look asap. I'll write you if I need to discuss the implementation.

**Comment by dwertent** [comment]
@alegrey91 Sure, I will reach out to you on Linkedin :)
This is a good question, we are working on updating the output to v2. 
In short - v1 output is mapping controls to resources and v2 output is mapping resources to controls.
