### ISSUE TITLE
Cannot scan HELM charts with all controls/frameowrks 

### ISSUE THREAD

**Issue by slashben** [armosec/kubescape#292]
Running `helm template <mychart> | kubescape scan -` fails while `helm template <mychart> | kubescape scan framework nsa -` works as expected

**Comment by dwertent** [comment]
We do not support input from stdin/yaml files when scanning all frameworks.
This is because the command `scan` is expecting to receive a command `framework`/`control` and not args

> executing `kubescape scan file.yaml` will fail, instead execute `kubescape scan framework nsa,mitre,armobest file.yaml`

**Comment by dwertent** [comment]
@slashben Thank you.
Run `helm template <mychart> | kubescape scan framework all -`, this will work.
