### ISSUE TITLE
Provide binary installation for other processor architectures

### ISSUE THREAD

**Issue by Willena** [armosec/kubescape#293]
A time of writing, the binary is only available for AMD64 architecture. 
Would it be possible to also provide other binary arch, such as ARM and ARM64 ?

**Comment by dwertent** [comment]
Same issue as #195.

Do you have an example of this? If you wish you are more than welcome to contribute this support :)
I do not understand why the build of macos  in [GitHub actions](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#github-hosted-runners)  is not on ARM

**Comment by dwertent** [comment]
Kubescape [images are built with arm support](https://github.com/armosec/armo-helm/releases/tag/armo-cluster-components-1.7.8)

**Comment by johnnyhuy** [comment]
Looks like the install script is still pulling down the AMD64 Kubescape binary on my ARM64 system.

```bash
$ curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
Installing Kubescape...

######################################################################## 100.0%

Finished Installation.

$ kubescape
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

Perhaps we can get an ARM64 release similar to the `ubuntu` and `mac` artifacts 🤞
