### ISSUE TITLE
Spelling error Namescape should be Namespace

### ISSUE THREAD

**Issue by clintmod** [armosec/kubescape#296]
https://github.com/armosec/kubescape/blob/3fad2f3430cd9cabb468b6f67999779a85e9eda5/resultshandling/printer/summeryhelpers.go#L25

**Comment by dwertent** [comment]
@clintmod  Thank you. Will be fixed!
If you wish, you can contribute by opening a PR to the `dev` branch with a fix :)

**Comment by clintmod** [comment]
@dwertent PR created
