### ISSUE TITLE
Slack Integration Token Length

### ISSUE THREAD

**Issue by jonaskint** [armosec/kubescape#298]
Hi, I'm testing out kubespace and tried out the Slack integration. I was following the documentation on the https://portal.armo.cloud/settings/integrations/slack page but ran into an error where my bot token is apparently the wrong length.
Is there anything that I'm overlooking or did I run against a bug?

```
kubester
400
Oooooops!
Something went wrong...
See more details
expand_less
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 400,
  "statusText": "OK",
  "url": "https://api.armo.cloud/api/v1/customerConfiguration?scope=customer&customerGUID=XXXXXXXXXXXXXX",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://api.armo.cloud/api/v1/customerConfiguration?scope=customer&customerGUID=XXXXXXXXXXXXXX: 400 OK",
  "error": "invalid token length\n"
}
```

**Comment by slashben** [comment]
@jonaskint we are checking, what is the length of your token?

**Comment by slashben** [comment]
> 56 characters The layout looks something like `xxxx-xxxxxxxxxxxx-xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx`

thanks! that helps a lot, there seems to be some misunderstanding on our side about the length. We will get back soon!

**Comment by slashben** [comment]
@jonaskint , we have pushed fix to our backend, can you please verify?

**Comment by jonaskint** [comment]
Yes, that change seems to have fixed it!
