### ISSUE TITLE
JSON FORMAT

### ISSUE THREAD

**Issue by sojugeorge** [armosec/kubescape#31]
The default output is printed in a pretty "console friendly" manner. But can we  retrieve them  in JSON format for further processing.

**Comment by dwertent** [comment]
@sojugeorge  We support json output format:
```
kubescape scan framework nsa --format json --output results.json
```

For more information please checkout [examples of our latest release ](https://github.com/armosec/kubescape/blob/master/docs/release.md)

Please confirm so we can close the issue :)

**Comment by sojugeorge** [comment]
Hi, Thanks for the update.  Actually we are running this tool in gitlab and its getting an error ERROR: Job failed: command terminated with exit code 127.


But

 kubescape scan framework nsa --format json 
 
can we run like this just to show the output in a json format. I dont want to save it as a json file.
