### ISSUE TITLE
kubescape fails with [Error] failed to init host sensor

### ISSUE THREAD

**Issue by swanand-gadre** [armosec/kubescape#318]
kubescape is failing with following error

[root@ssc-vm-g2-rhev4-2905 ~]# kubescape scan framework nsa -e kube-system,kube-public,calico-system,tigera-operator,kube-node-lease,calico-apiserver --enable-host-scan
ARMO security scanner starting
[progress] Installing host sensor
[Error] failed to init host sensor
Warning: failed to get policies from github release, loading policies from cache
Warning: failed to get config inputs from github release, this may affect the scanning results
[progress] Downloading/Loading policy definitions
open /root/.kubescape/nsa: no such file or directory

----------

I am referring -> https://github.com/armosec/kubescape

[root@ssc-vm-g2-rhev4-2696 ~]# kubescape scan framework nsa --enable-host-scan
ARMO security scanner starting
[progress] Installing host sensor
[Error] failed to init host sensor
Warning: failed to get policies from github release, loading policies from cache
Warning: failed to get config inputs from github release, this may affect the scanning results
[progress] Downloading/Loading policy definitions

-------------------

[root@ssc-vm-g2-rhev4-2696 ~]# kubescape scan
ARMO security scanner starting
Warning: Kubernetes cluster nodes scanning is disabled. This is required to collect valuable data for certain controls. You can enable it using  the --enable-host-scan flag
Warning: failed to get policies from github release, loading policies from cache
Warning: failed to get config inputs from github release, this may affect the scanning results
[progress] Downloading/Loading policy definitions

---------------
[root@ssc-vm-g2-rhev4-2905 ~]# kubescape download nsa/C-0001 -o nsa.json
Error: requires two arguments : framework/control <framework-name>/<control-name>

-----------------

[root@ssc-vm-g2-rhev4-2905 ~]# kubescape download framework nsa --output nsa.json
error: error getting: ControlID_RuleName from: 'https://github.com/armosec/regolibrary/releases/latest/download' ,error: HTTP request failed. URL: '/armosec/regolibrary/releases/download/v1.0.133/ControlID_RuleName', HTTP-ERROR: '404 Not Found', BODY: '

**Comment by slashben** [comment]
@swanand-gadre , hi!
We have been experiencing issues around the frameworks and controls in the last 18 hours (see https://github.com/armosec/regolibrary/actions/workflows/export.yaml) and they should've been fixed ~3 hours ago. 

Do you still seeing these issues?

**Comment by swanand-gadre** [comment]
Thanks @slashben 

It started working

But I am still seeing this error

---------------


[root@ssc-vm-g2-rhev4-2905 ~]# kubescape scan framework nsa -e kube-system,kube-public,calico-system,tigera-operator,kube-node-lease,calico-apiserver --enable-host-scan
ARMO security scanner starting
[progress] Installing host sensor
[Error] failed to init host sensor

**Comment by slashben** [comment]
@swanand-gadre , what is the type of your cluster? Is it a managed cluster? Do you have some policy engine in place? (like OPA-Gatekeeper or Kyverno)

**Comment by swanand-gadre** [comment]
Hi @slashben 

Thanks for quick response.

I am using kubernetes cluster
Regarding policy engine, no I am not using policy engines.

I am closing this issue now, that I am able to scan 

Regards
Swanand
