### ISSUE TITLE
proposal: consider make result metrics colorful for `% RISK-SCORE` by passing --color flag

### ISSUE THREAD

**Issue by Dentrax** [armosec/kubescape#320]
For example;
* if `% RISK-SCORE` **==** `0%` then make _text_ color `green`
* if `% RISK-SCORE` **>=** `30%` then make _text_ color `yellow`
* if `% RISK-SCORE` **>=** `70%` then make _text_ color `red`
* if `% RISK-SCORE` **==** `100%` then make _background_ color `red`
* if `% RISK-SCORE` **==** `100%` then make _background_ color `red`
* if `% RISK-SCORE` **==** `skipped` then make _background_ color `yellow`

The _colors_ and _percentages_ here are representative. These ratios may vary depending on the use-cases. Just dropping the idea here to further discussion.

**Comment by slashben** [comment]
Nice idea! I like it!

Would you like to contribute? We can help with the code

**Comment by dwertent** [comment]
@Dentrax this is a good idea.
We need to think exactly where to print these colorful results, where you referring to the summary table or the detailed results?
Also, we need to think of the color scheme when the `--fail-threshold` flag is in use

**Comment by Lucifergene** [comment]
I want to work on this issue.

**Comment by dwertent** [comment]
@Lucifergene Sure!
If you wish we can set a meeting and discuss the matter :)

**Comment by falconcode16** [comment]
Hey @dwertent ! I'm new to contributing. Where can I help in this issue?

**Comment by Lucifergene** [comment]
> @Lucifergene Sure!
> 
> A few thoughts I have:
> 
> 1. We will support `--them` flag, when set to `bright` we will not use colors
> 2. Do we want to color only the final result or also each results in the summary table?
> 3. We will support [pdf](https://github.com/armosec/kubescape/pull/396), I think we should add colors to that as well
> 
> If you wish we can set a meeting and discuss the matter :)

Working on it!

**Comment by dwertent** [comment]
@Lucifergene If you have any questions feel free to contact me dwertent@armosec.io :)
I am working on upgrading the output table as we speak, please clone the [dev branch](https://github.com/armosec/kubescape/tree/dev) and run kubescape with the `output-version v2` flag. Let me know what you think 🙃

@falconcode16 Thank you for your willingness to contribute :) If you wish to contribute other features I tried to tag them with the [open for contribution tag](https://github.com/armosec/kubescape/issues?q=is%3Aissue+is%3Aopen+label%3A%22open+for+contribution%22). 
In any event, do not hesitate to reach out to me with suggestions of other features you think users of the tool will appreciate.

**Comment by dwertent** [comment]
Thank you @Lucifergene  for adding the severity column: 

![Screen Shot 2022-05-03 at 11 32 57](https://user-images.githubusercontent.com/64066841/166424827-90176ae5-340f-415c-9b50-eeb02506e9c0.png)
