### ISSUE TITLE
Can't download framework definition

### ISSUE THREAD

**Issue by gabbueno** [armosec/kubescape#33]
Is there an alternate way to get nsa definitions?
I'm trying to run kubescape behind a firewall with no internet access

$ ./kubescape scan framework nsa --exclude-namespaces kube-system,kube-public
ARMO security scanner starting
[progress] Downloading framework definitions
Could not download framework, please check if this framework exists

**Comment by dwertent** [comment]
@gabbueno We added [support for offline scanning](https://github.com/armosec/kubescape/blob/master/README.md#offline-support-).

Please confirm so will close the ticket 😄
