### ISSUE TITLE
Error installing the Helm chart as part of image scanning

### ISSUE THREAD

**Issue by sprathod369** [armosec/kubescape#353]
I'm trying to install the Helm chart to explore the image scanning (beta) & RBAC (beta) feature as part of vulnerability scan in my K8s environment. 
However the installation fails as there seems to be some failure with post-install as seen below
```
helm upgrade --install armo  armo/armo-cluster-components -n armo-system --create-namespace --set accountGuid=<xxxxxxx> --set clusterName=`kubectl config current-context`
Release "armo" does not exist. Installing it now.
Error: failed post-install: timed out waiting for the condition
```

Another attempt to install but this time there seems to be some failure with post-upgrade hooks as seen below
```
helm upgrade --install armo  armo/armo-cluster-components -n armo-system --create-namespace --set accountGuid=<xxxxxxx> --set clusterName=`kubectl config current-context`
Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition
```

Post installation validation check for reference
```
kubectl -n armo-system get pods
NAME                                         READY   STATUS             RESTARTS   AGE
armo-collector-6c6f487878-t98dc              0/1     ImagePullBackOff   0          4h21m
armo-kubescape-1643356800-sjvt4              0/1     ImagePullBackOff   0          3h16m
armo-kubescape-post-install-hook-wrqsq       0/1     ImagePullBackOff   0          6m18s
armo-notification-service-7c87c76cfb-vrd9k   0/1     ImagePullBackOff   0          4h21m
armo-vuln-scan-5855c8f7b8-k7h9h              0/1     ImagePullBackOff   0          4h21m
armo-web-socket-699499df8f-c2m5p             0/1     ImagePullBackOff   0          4h21m
```

**Comment by dwertent** [comment]
Hi @sprathod369 , it looks like an issue pulling the images. The images are public, so I'm not sure why you are encountering such an issue in your cluster.
Please check the event message when running the `kubectl describe` ->
```
kubectl -n armo-system describe pod armo-collector-6c6f487878-t98dc
```

**Comment by sprathod369** [comment]
@dwertent - Thanks for the inputs. 
Based on the event message, it seems I'll have to troubleshoot the certificate issue and investigate further on issue pulling the image (firewall blocking them on my side or something else)

`Failed to pull image "quay.io/armosec/k8s-ca-dashboard-aggregator-ubi:183": rpc error: code = Unknown desc = Error response from daemon: Get "https://quay.io/v2/": x509: certificate signed by unknown authority`

**Comment by dwertent** [comment]
@sprathod369 Did you manage to fix this? I see similar issues where opened [on kubernetes](https://github.com/kubernetes/kubernetes/issues/43924) and [here](https://github.com/bitnami-labs/sealed-secrets/issues/332)

**Comment by dwertent** [comment]
I am closing this issue since it is not a kubescape issue but a proxy/FW configuration
