### ISSUE TITLE
Docker container for v2 still thinks it is v1

### ISSUE THREAD

**Issue by sboschman** [armosec/kubescape#374]
Container with latest v2 tag complains it is not the latest version, see #215 as well.

```
$ docker run -ti --rm quay.io/armosec/kubescape:v2.0.144 version
Warning: 'kubescape' is not updated to the latest release: 'v2.0.144'
Your current version is: v1.0.144
```

I guess the [Dockerfile](https://github.com/armosec/kubescape/blob/master/build/Dockerfile#L6) needs a version bump.

**Comment by dwertent** [comment]
Thank you @sboschman for pointing this out.
Will be fixed next release :)
