### ISSUE TITLE
[fatal] open /root/.kubescape/nsa: no such file or directory

### ISSUE THREAD

**Issue by neblen** [armosec/kubescape#376]
When I use kubescpae to scan k8s cluster in a offline enviorment, there is a error.
```
Coomand:./kubescape-ubuntu-latest download framework nsa --output nsa.json
Warning: failed to get policies from github release, loading policies from cache
[fatal] open /root/.kubescape/nsa: no such file or directory.
```

**Comment by dwertent** [comment]
Hi @neblen and thank you for asking.

This message, `Warning: failed to get policies from github release, loading policies from cache` indicates kubescape failed to download the `nsa` framework, please check your network connectivity.

For the offline support, you first need to download the artifacts where you have a network connection and then copy the downloaded artifacts to the offline environment ->

1. With network
    ```
    kubescape download artifacts --output path/to/local/dir
    ```
2. Copy to your air-gaped environment
3. Scan
    ```
    kubescape scan framework nsa --use-artifacts-from path/to/local/dir
    ```

If you wish, you can download the released artifacts from [here](https://github.com/armosec/regolibrary/releases/tag/v1.0.153)

**Comment by neblen** [comment]
@dwertent  Thank you very much! Just now，I download nsa.json with Internet and copy nsa.json to offline enviornment。Finally kubescape work rightly.

**Comment by dwertent** [comment]
I will update the docs that there should not be a misleading :)

**Comment by neblen** [comment]
> I will update the docs that there should not be a misleading :)

That's great! Maybe some people have the same problems as me.
