### ISSUE TITLE
armo-vuln-scan pod are evicted

### ISSUE THREAD

**Issue by lamenawuer** [armosec/kubescape#389]
When deploying this as a cronjob in kubernetes random arno-vuln-scan pods are evicted due to disk pressure:

Pod logs:
[...]
│ Status:  Failed  
│ Reason:  Evicted   
│ Message: The node was low on resource: ephemeral-storage. Container armo-vuln-scan was using 7197816Ki, which exceeds its request of 0.
[...]

Node logs:
[...]
| Normal   NodeHasDiskPressure    21m (x25 over 8d)  kubelet  Node <my_node_ip> status is now: NodeHasDiskPressure 
│ Warning  EvictionThresholdMet   15m (x37 over 8d)  kubelet  Attempting to reclaim ephemeral-storage                        
│ Normal   NodeHasNoDiskPressure  10m (x25 over 8d)  kubelet  Node <my_node_ip> status is now: NodeHasNoDiskPressure
[...]

Is this a normal behavior? Before configuring the node to increase the ephemeral space quota I'd like to know if it is normal for a vulnerability scan pod to claim that much space

Thanks and regards

**Comment by dwertent** [comment]
Hi @lamenawuer , in general the vulnerability component downloads the vulnerabilities db so it does require some memory.
But if I understood correctly it using more than 7gb, this is unusual.
Are you running a particularly large cluster? Approximately how many workloads are running in the cluster?

**Comment by lamenawuer** [comment]
Hi @dwertent thanks for your answer. My infrastructure isn't particularly big. Right now there are none as when I turn on kubescape it just starts evicting pods... But if it were on there is only one pod for the vulnerability scan active at a time

**Comment by dwertent** [comment]
@slashben @Bezbran  Do we have any lead over here?

**Comment by dwertent** [comment]
Thank you @slashben .
@lamenawuer  Please update the helm chart

**Comment by lamenawuer** [comment]
I don't know why you closed this issue, I haven't yet reported that your update worked, which it didn't. I updated the helm version and the pods still make the node have the disk pressure state and thus get evicted again and again. I don't see how the new helm chart version will solve this problem... the deployment has no quota/resource management

**Comment by dwertent** [comment]
@lamenawuer  Sorry, my apologies. I was under the impression it had been solved 😕.

When you run -> `kubectl -n armo-system describe deployments.apps armo-vuln-scan`
Do you see the following resource limits:
```
    Limits:
      cpu:                1500m
      ephemeral-storage:  8Gi
      memory:             1000Mi
    Requests:
      cpu:                300m
      ephemeral-storage:  2Gi
      memory:             200Mi
```

If not, the helm was not updated.

If the helm was update, I will like to have a short session with you (if possible) so we can investigate this issue further :)

**Comment by lamenawuer** [comment]
@dwertent no worries, and thanks a lot for your reactivity. Indeed I see the ephemeral storage limit/request. When I was looking at the chart itself I overlooked the values. My output:
`    Limits:
      cpu:                1500m
      ephemeral-storage:  8Gi
      memory:             1000Mi
    Requests:
      cpu:                300m
      ephemeral-storage:  2Gi
      memory:             200Mi
`
The limits/requests are indeed there but the node keeps getting disk pressure on and off as the pods are being evicted. Sure, a one to one sesion would really be helpful I think

**Comment by dwertent** [comment]
@lamenawuer You can increase the requests to 8Gi (and also the limit). I guess that will patch the issue for now. 
I can reach out to you, what is you email/linkedin?
Alternatively you can reach out to me to my [linkedin](https://www.linkedin.com/in/david-wertenteil-0ba277b9).

**Comment by lamenawuer** [comment]
@dwertent I increased the disk size to a more fitting one and raised the ephemeral quota in the chart, and armo-vuln-scan rusn just fine!  You can close the issue, 

Thanks a lot for your help and swiftness
