### ISSUE TITLE
kubescape does not submit to armo cloud for control scans

### ISSUE THREAD

**Issue by avinashupadhya99** [armosec/kubescape#414]
Scanning specific controls in kubescape CLI does not submit to the ARMO cloud backend even with the presence of the `customerGUID` in the config and the usage of the `--submit` flag. Scanning specific frameworks submits the results to the ARMO cloud backend.
![image](https://user-images.githubusercontent.com/52544819/155264261-68531a9c-3811-4092-84e0-7ef285feb681.png)

**Comment by dwertent** [comment]
Hi @avinashupadhya99 
By definition Kubescape does not submit the scan results when scanning a single controls. I will try to clarify this in the output message.
If you wish to submit the scan results of a single control, you can create a [custom framework](https://youtu.be/12Sanq_rEhs) with that control and scan the framework.
@rotemamsa According to the roadmap, will this behavior change in the future?

**Comment by amirkCA** [comment]
You can always place the control in a framework and submit it

**Comment by avinashupadhya99** [comment]
Thank you for clearing it. The video explained it really it well. Sorry for the confusion, I expected similar behaviour between frameworks and controls. I'm just curious about why the individual control scans are not submitted? This is not really an issue for me, just wanted to know the idea behind it.

**Comment by amirkCA** [comment]
we decided to scan frameworks and show results per framework. This is the design we did. and it can solve all use cases including running a framework with a single control....

**Comment by dwertent** [comment]
The SaaS is designed for following trends and risk score over time.
Because the risk-score is calculated in the framework scope, only results of frameworks are reported.

I'm happy to hear the video explains the topic, let me know if you think there are more videos I can create so I can cover more topics :)
