### ISSUE TITLE
Images from allowed registry

### ISSUE THREAD

**Issue by clintmod** [armosec/kubescape#415]
```
bash-4.2# kubescape version
Skipping version check
Your current version is: v1.0.137
```

I tried to set a local config file that looks like this:
```
bash-4.2# cat ~/.kubescape/config.json 
{ "imageRepositoryAllowList": "ecr.*amazonaws.com,.*.gcr.io,*azurecr.io,.*my-artifact-repo.*" }
```

I also tried a file that looks like this:
```
{
  "imageRepositoryAllowList": [
    "ecr.*amazonaws.com",
    ".*.gcr.io,*azurecr.io",
    ".*my-artifact-repo.*"
  ]
}
```

neither one seemed to work the check is still failing:

any ideas?

**Comment by dwertent** [comment]
Hi @clintmod and thank you for asking.

First, you will need to [update your kubescape version](https://github.com/armosec/kubescape#install).

Next, do as following:

1. Download the control configuration file

    ```
    kubescape download controls-inputs
    ```
    The configuration file will be downloaded and stored in the default cache directory -> `~/.kubescape/controls-inputs.json`
2. Edit the `~/.kubescape/controls-inputs.json` so it will suit your needs
3. Scan your cluster with the `--controls-config ~/.kubescape/controls-inputs.json`
    e.g.:
    ```
    kubescape scan --controls-config ~/.kubescape/controls-inputs.json  --enable-host-scan --submit
    ```

**Comment by clintmod** [comment]
I don't have an account to download anything from… trying to set this up manually

**Comment by dwertent** [comment]
Closing since I have not received a response. If you wish, feel free to contact me personally- dwertent@armosec.io
