### ISSUE TITLE
Unusual version warning while executing `kubescape version`

### ISSUE THREAD

**Issue by Atharva-Shinde** [armosec/kubescape#417]
I installed kubescape by running [these commands](https://github.com/armosec/kubescape#install-on-macos).

After executing `kubescape version` I get a warning "kubescape is not updated to the latest release: 'V2.0.148',
So I tried to upgrade by `brew upgrade kubescape` and got a prompt: `warning kubescape 2.0.148 already installed`

Here's a screenshot:
<img width="583" alt="Screenshot 2022-02-25 at 7 31 03 PM" src="https://user-images.githubusercontent.com/69111235/155739082-f273c70d-e7ad-4e68-aaae-eddfc80418ea.png">

Nevertheless I haven't encountered any other problem while working with Kubescape.
Is there something I'm missing?

**Comment by avinashupadhya99** [comment]
This seems to be an issue with the `brew` installation. The character `v` is missing at the start of the version. Regular installation does not seem to have this issue.

**Comment by dwertent** [comment]
@rotemamsa Are there any updates? Is this fixed?

**Comment by rotemamsa** [comment]
@avinashupadhya99 @dwertent still on it, there is an issue updating the brew just like that, investigating and ill update shortly

**Comment by gromgit** [comment]
While the Homebrew PR is in progress, it should be noted that this:
https://github.com/armosec/kubescape/blob/7847a4593b21606204da5e422450bf21cddc4578/cautils/versioncheck.go#L100

is just wrong. Comparing versions as _strings_ fails when any version component rolls over into the next order of magnitude; did anyone noticed what happened when `2.0.99` got bumped to `2.0.100`?

For a quick-n-dirty fix, you should use https://pkg.go.dev/golang.org/x/mod/semver instead, or some other semantic versioning library. I'm not a Go programmer, but it seems like:
```
if BuildNumber != "" && semver.Compare(BuildNumber, latestVersion.ClientUpdate) < 0 { 
```
(plus the necessary import) should Do The Right Thing every time.

**Comment by dwertent** [comment]
Thank you @gromgit for pointing it out.
Will be fixed asap :)

**Comment by rotemamsa** [comment]
Homebrew PR was approved, closing the issue.
