### ISSUE TITLE
Error installing the Helm Charts for Armo collector pods | Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by sprathod369** [armosec/kubescape#422]
Installed the Helm chart to explore the image scanning in my K8s environment. However, as part of installation there seems to be some failure with "helm upgrade --install armo" command as seen below

```
Release "armo" does not exist. Installing it now.
Error: failed post-install: timed out waiting for the condition

```
Another attempt as part of helm upgrade command gives
`Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition`

A quick status check on armo pods 
```
kubectl -n armo-system get pods
NAME                                         READY   STATUS      RESTARTS   AGE
armo-collector-5bf574d698-mgddf              0/1     Completed   1          10m
armo-collector-6b448cccdc-gwcdv              0/1     Running     3          17m
armo-notification-service-845466b457-27zcb   1/1     Running     0          10m
armo-vuln-scan-6c5b9955bb-jl9wt              1/1     Running     0          10m
armo-web-socket-66f7dc766d-5nc7q             0/1     Running     0          10m
armo-web-socket-fbf96f9f5-q6t8b              0/1     Running     0          17m
```
kubectl -n armo-system get pods
```
NAME                                         READY   STATUS             RESTARTS   AGE
armo-collector-5bf574d698-mgddf              0/1     CrashLoopBackOff   3          20m
armo-collector-6b448cccdc-gwcdv              0/1     CrashLoopBackOff   4          27m
armo-notification-service-845466b457-27zcb   1/1     Running            0          20m
armo-vuln-scan-6c5b9955bb-jl9wt              1/1     Running            0          20m
armo-web-socket-66f7dc766d-5nc7q             0/1     Running            0          20m
armo-web-socket-fbf96f9f5-q6t8b              0/1     Running            0          27m

```

kubectl describe pod for the armo-collector indicates
```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  30m                  default-scheduler  Successfully assigned armo-system/armo-collector-6b448cccdc-gwcdv
  Normal   Pulling    30m                  kubelet            Pulling image "quay.io/armosec/k8s-ca-dashboard-aggregator-ubi:185"
  Normal   Pulled     29m                  kubelet            Successfully pulled image "quay.io/armosec/k8s-ca-dashboard-aggregator-ubi:185" in 34.639658932s
  Normal   Created    29m                  kubelet            Created container armo-collector
  Normal   Started    29m                  kubelet            Started container armo-collector
  Warning  Unhealthy  28s (x298 over 29m)  kubelet            **Readiness probe failed: HTTP probe failed with statuscode: 503**

```

The readiness probe is failing (as seen above) for the armo-collector pods. Any inputs / suggestions on what seems to be the issue and resolution will be appreciated?

**Comment by dwertent** [comment]
Thank you @sprathod369 . I did not see this issue in the past. Is it possible your network is slow?
@Bezbran What are your thoughts regrading handling this is the future?

**Comment by Bezbran** [comment]
Hi @sprathod369, as @dwertent mentioned, this isn't a common failure we saw so far.
One thing you can check is the connection to `*.armo.cloud` servers is opened in your Firewall.

In addition, if you can attach the pod logs it will be very helpful. Just hide any sensitive data before attaching it here.

**Comment by sprathod369** [comment]
Here are the pod logs for the collector @dwertent

```
# kubectl -n armo-system logs armo-collector-5bf574d698-t4sxl
-include-namespaces=armo-system not exists.
Image version: 185
E0301 06:30:12.916725       8 podwatch.go:536] Found nil element in pdm
E0301 06:30:12.970719       8 podwatch.go:536] Found nil element in pdm
E0301 06:30:24.046450       8 websocket.go:72] x509: certificate signed by unknown authority
E0301 06:31:07.744920       8 websocket.go:72] x509: certificate signed by unknown authority
E0301 06:31:31.954473       8 podwatch.go:536] Found nil element in pdm
E0301 06:31:31.954582       8 podwatch.go:536] Found nil element in pdm
E0301 06:31:59.441696       8 websocket.go:72] x509: certificate signed by unknown authority
E0301 06:33:54.182791       8 websocket.go:72] x509: certificate signed by unknown authority
E0301 06:35:00.899340       8 websocket.go:72] x509: certificate signed by unknown authority
E0301 06:35:00.899394       8 websocket.go:76] cant connect to websocket after 5 tries
E0301 06:35:00.899401       8 websocket.go:91] cant connect to websocket after 5 tries
E0301 06:35:00.899408       8 main.go:64] cant connect to websocket after 5 tries
```

**Comment by Bezbran** [comment]
@sprathod369, thanks for the logs.
Is there any chance you have some MIDM whose change our original certificate to one of your own?

Here are the details of our certificate:

![image](https://user-images.githubusercontent.com/5871018/156124823-85b89f7a-8036-41a5-aa50-b68b8f1ec8a4.png)

**Comment by sprathod369** [comment]
@Bezbran - Not sure if I understand the above point. I have successfully performed the cluster scan (using all 4 frameworks) from this same kubernetes environment & I can see the results published on the UI at https://portal.armo.cloud/configuration-scanning/ So is there still a possibility that the connection to *.armo.cloud servers are blocked in the Firewall while attempting the image scanning (beta) feature? I'll check with my networking team but if you have any specific pointers / suggestions please let me know. Thanks!!

**Comment by Bezbran** [comment]
Hi @sprathod369, can we set a call to check the situation?
Here is my email, bbrandwine@armosec.io, feel free to contact me.

Regarding the results on the UI, can you see the results of the daily scanning as well, or just your first scan?

**Comment by Bezbran** [comment]
I see no comment regarding this issue anymore, assuming it was solved.

**Comment by sprathod369** [comment]
@Bezbran - Sorry for the tardy reply, was OOO for the past few days.
Regarding the results on the UI for cluster configuration scanning, I can see the historical results of the past few runs that I had triggered
The latest update on Image scanning is that I can see the collector pod running now (no longer see "CrashLoopBackOff" status) - network team helped me address this .... maybe a certificate issue or some blocking firewall issue on my side. 

Here's the latest snapshot status of the armo pods
```
# kubectl -n armo-system get pods
NAME                                         READY   STATUS      RESTARTS   AGE
armo-collector-5bf574d698-t4sxl              1/1     Running     1790       8d
armo-notification-service-845466b457-27zcb   1/1     Running     0          9d
armo-scan-scheduler-27443520-cd7rp           0/1     Completed   0          2d12h
armo-scan-scheduler-27444960-vczl9           0/1     Completed   0          36h
armo-scan-scheduler-27446400-z29qd           0/1     Completed   0          12h
armo-vuln-scan-6c5b9955bb-jl9wt              1/1     Running     0          9d
armo-web-socket-66f7dc766d-pn54b             0/1     Running     0          8d
armo-web-socket-fbf96f9f5-q6t8b              0/1     Running     0          9d
```

Pod logs for the collector
```
# kubectl -n armo-system logs armo-collector-5bf574d698-t4sxl
-include-namespaces=armo-system not exists.
Image version: 185
E0309 11:53:09.652733       8 podwatch.go:536] Found nil element in pdm
E0309 11:53:09.653745       8 podwatch.go:536] Found nil element in pdm
E0309 11:53:23.656736       8 podwatch.go:536] Found nil element in pdm
E0309 11:53:23.656761       8 podwatch.go:536] Found nil element in pdm
E0309 12:29:21.084744       8 secretwatch.go:98] Got unexpected secret from chan: &{ <nil>}
Log level: 2, set -stderrthreshold=INFO for detailed logs/k8s-ca-dashboard-aggregator -include-namespaces=armo-system 2>&1  exited with code 4
Image version: 185
E0309 12:29:33.653732      25 podwatch.go:536] Found nil element in pdm
E0309 12:29:33.654300      25 podwatch.go:536] Found nil element in pdm
E0309 12:29:38.657979      25 podwatch.go:536] Found nil element in pdm
E0309 12:29:38.658002      25 podwatch.go:536] Found nil element in pdm

```

However, I do not see any results on the for Image scanning at https://portal.armo.cloud/image-scanning. 
What seems to be missing - anything potentially to do with the web-socket pod ?
Happy to talk to you if required. Thanks for the support!!

**Comment by Bezbran** [comment]
Both web-socket and vuln-scan are required for image scanning.
Both are required egress access.
We are working on some list of servers should be opened in FW in order to make it works.
Send me a mail if you want us to take a closer look.

bbrandwine@armosec.io
