### ISSUE TITLE
Flag for disabling colored output 

### ISSUE THREAD

**Issue by dwertent** [armosec/kubescape#434]
There are some terminals who do not display colored ouput properly. For such cases kubescape needs to support a flag (so as `--plain-output`) that when used, the output (stdout/stderr) will be without colors at all.

If you wish to take this upon yourself, please contact [one of the maintainers](https://github.com/armosec/kubescape/blob/master/MAINTAINERS.md) for more information 😀

**Comment by Akasurde** [comment]
@dwertent Can we please close this since #445 is merged? Thanks.

**Comment by dwertent** [comment]
@Akasurde I think it's better we close it when we release a new version :)
