### ISSUE TITLE
Implement Azure AKS integration for Kubescape

### ISSUE THREAD

**Issue by slashben** [armosec/kubescape#438]
Kubescape uses Kubernetes vendor information to give enhanced security information about the cluster.

As of today, it supports AWS EKS and GCP GKE APIs.

Need to add support for Azure AKS. Kubescape need the access to the cluster description API, see [here](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/get)

**Comment by slashben** [comment]
@dwertent , can you please add an example implementation for contributors to look at? Thanks!

**Comment by roberthstrand** [comment]
As mentioned in the [Azure Cloud Native meetup](https://www.meetup.com/azure-cloud-native/events/284200837/) with Amir today, we're very open to help in anything related to the Kubescape integration with Azure AKS. Feel free to reach out 🖖

**Comment by dwertent** [comment]
Thank you @roberthstrand very much :)
