### ISSUE TITLE
armo-vuln-scan pod CrashLoopBackOff

### ISSUE THREAD

**Issue by LiorHaim** [armosec/kubescape#446]
Hello,

After installing using the helm chart, my armo-vuln-scan pod keeps crashing (CrashLoopBackOff).
After checking the logs I got this:
```
2022/03/10 12:49:22 OCIMAGE_URL/CA_OCIMAGE_URL is not configured- some features might not work, please install OCIMAGE to get more features
2022/03/10 12:49:22 open /etc/vuln-scan/anchore-resources/.grype/config.yaml: no such file or directory
```

I also noticed that the OCIMAGE_URL variable was with an empty value, could it be related? 

Thank you!

**Comment by LiorHaim** [comment]
@Bezbran quay.io/armosec/k8s-ca-vuln-scan-ubi:117

**Comment by Bezbran** [comment]
@LiorHaim, I see this is the last updated image.
Can you please attach the pod YAML here (delete any sensitive information like GUIDs or cluster name)?

Basically at the start of the container we are generating some anchor default config file in the container file system, then we are copy-pasting it for each container scan.
Looks like we can't find this default config file at the beginning, so I suspect we were unable to generate it on the disk.

The OCIMAGE_URL is irrelevant for now.
If you want us to take a closer look, please contact us in mail bbrandwine@armosec.io to schedule a meeting.

**Comment by Bezbran** [comment]
@LiorHaim , I see no new comment for more than a week. 
I guess the issue was solved.
Feel free to keep contact us for any improvement.
