### ISSUE TITLE
Error during host-scan on OpenShift

### ISSUE THREAD

**Issue by fvogl** [armosec/kubescape#469]
With --enable-host-scan using a custom host-scan yaml file (to get it working in first place) on OpenShift I get this error from all daemonset PODs.

[error] failed to get data. path: /kubeletConfigurations; podName: host-scanner-5tzwr; error: an error on the server ("failed to sense kubelet conf: failed to LocateKubeletProcess: no process with given suffix found") has prevented the request from succeeding (get pods http:host-scanner-5tzwr:7888)

**Comment by dwertent** [comment]
Hi @fvogl, can you please share the custom yaml? what did you change from the default yaml?

**Comment by fvogl** [comment]
I've created a serviceaccount, used it in the daemonset spec, and gave it privileged access using
```sh
oc adm policy add-scc-to-user privileged -z host-scanner -n kubescape-host-scanner
```

**Comment by dwertent** [comment]
Thank you for reporting this. We will investigate :)

**Comment by Bezbran** [comment]
Hi @fvogl , thank you for pointing this out.
We update the host-sensor so it will support kubelet in OpenShift hosts.

Please try again and verify it is fixed.

**Comment by fvogl** [comment]
Thanks @Bezbran for the quick fix!

**Comment by Bezbran** [comment]
You welcome
