### ISSUE TITLE
--fail-threshold throwing syntax error in recent version v2.0.150

### ISSUE THREAD

**Issue by VarshaRuthu824** [armosec/kubescape#470]
**Command**: kubescan control framework nsa -t 0
**Result:**
Error: scan risk-score 21.59 is above permitted threshold 0.00
Usage:
  kubescape scan control <control names list>/<control ids list> [flags]

Examples:

  # Scan the 'privileged container' control
  kubescape scan control "privileged container"
	
  # Scan list of controls separated with a comma
  kubescape scan control "privileged container","allowed hostpath"
  
  # Scan list of controls using the control ID separated with a comma
  kubescape scan control C-0058,C-0057
  
  Run 'kubescape list controls' for the list of supported controls

Because of the above issue, kube scape scan is passing even when there's failure!

**Comment by dwertent** [comment]
Thank you @VarshaRuthu824 for opening this issue.
Will be fixed ASAP.
