### ISSUE TITLE
Question: Authentication and Authorization methods when scanning cluster 

### ISSUE THREAD

**Issue by JustinYeoh93** [armosec/kubescape#471]
Hi there KubeScape community!

Thank y'all for this wonderful system, with this I am finally able to give quantifiable justifications on my cluster's security state.

I've been trying to build a CI/CD system that frequently scans the cluster (not just manifest) for security vulnerbalities.
Running a full cluster scan using a local `~./kube/config` is fine for local scanning, but when I want to do scanning with third party tools like GitHub Actions, I find myself stuck at the authencation and authorization stage.

I've read in the docs https://hub.armo.cloud/docs/github-1 that my CI/CD would require access to the cluster.
So, my question is, other than putting a `~./kube/config` file in my CI/CD runner, what other authentication methods are there to do full cluster scans?

What I was thinking was to run a cronjob of such within the cluster and assign it a specific RBAC. Whether that is implementable, I'm uncertain.
Any tips would be much appreciated!

Thanks again!

Regards,
Justin

**Comment by dwertent** [comment]
Hi @JustinYeoh93 , my apologies for not replying earlier.

We released a helm chart for running in your cluster! [Check it out](https://hub.armo.cloud/docs/installation-of-armo-in-cluster) and feel free to [contact us](https://github.com/armosec/kubescape/blob/master/MAINTAINERS.md) if you have any further questions :)
