### ISSUE TITLE
Invalid customer id

### ISSUE THREAD

**Issue by ampc** [armosec/kubescape#475]
$ kubescape download artifacts --output .
[error] error downloading. artifact: controls-inputs; error: http-error: '400 Bad Request', reason: 'invalid customerGUID: invalid UUID length: 12'
[error] error downloading. artifact: exceptions; error: http-error: '400 Bad Request', reason: 'invalid customerGUID: invalid UUID length: 12'

**Comment by Bezbran** [comment]
Hi @ampc, basically this could happen when you are using some account ID didn't come from ARMO portal.
Deletion of kubescape folder deletes the kubescape config file with the corrupted account ID.

So can get a brand new valid account ID for free either by run `kubescape scan --submit` or by login into https://portal.armo.cloud/.
