### ISSUE TITLE
kubecape not rendering rbac map

### ISSUE THREAD

**Issue by xxradar** [armosec/kubescape#503]
Hi,
Is there any reason why kubescape is not rendering the rbac map?
I'm using https://portal.armo.cloud/dashboard with gitj=hub account
I'm getting a white empty map (firefox, chrome)

```
$ kubescape submit rbac -l debug   --account xxxxxxx
[debug] Armo URLs. api: api.armo.cloud; auth: auth.armo.cloud; report: report.armo.cloud; UI: portal.armo.cloud
[debug] . account ID: xxxxxx
[success] Data has been submitted successfully


You can see the results in a user-friendly UI, choose your preferred compliance framework, check risk results history and trends, manage exceptions, get remediation recommendations and much more by registering here: https://portal.armo.cloud/configuration-scanning/kubernetes-admin@kubernetes
```

**Comment by dwertent** [comment]
Hi @xxradar , 
There should be a dropdown listing the submitted cluster, you must select a cluster from that list. 
 -> 

![image](https://user-images.githubusercontent.com/64066841/167287953-6059fcb2-ea28-4814-94b1-668696682110.png)

LMK if the list is empty or if it's not working :)

**Comment by xxradar** [comment]
Hi @dwertent, thx, but it is checked. I even tried with different accounts and different scans. No success.

**Comment by zhujik** [comment]
I have the same error. Looking at the console, this is the error that i get:
```
GET https://api.armo.cloud/k8srestapi/v1/cluster?cluster=arn-aws-eks-eu-north-1-123456789012-cluster-my-cluster&customerGUID=abcdefgh-123456789-dasdafff 404
```

**Comment by dwertent** [comment]
Interesting. @zhujik  Can we have a quick call sometime? 
Feel free to contact me via [email](dwertent@armosec.io) or discord: dwertent#8111

**Comment by dwertent** [comment]
Closing since since issues seems to be resolved
