### ISSUE TITLE
armoCollector and armoVulnerabilityScanner source code?

### ISSUE THREAD

**Issue by zhujik** [armosec/kubescape#508]
Hello, I was trying to look into / improve the source code for those two deployments (coming with the offical helm charts). However, I don't seem to be able to find those. The helm charts point to 
* https://github.com/armosec/ca-vuln-scan
* https://github.com/armosec/k8s-armo-collector

however, both result in 404.

**Comment by dwertent** [comment]
Right, they are both still private repositories. We are working on opening them so they will be public.

For now I agree with you, we do not need to run these two microservices when the `submit` is false. We will need to change the behavior once we will support scrapping of the image vulnerabilities results.
