### ISSUE TITLE
Cant download images from quay.io/armosec

### ISSUE THREAD

**Issue by mustufa5689** [armosec/kubescape#531]
Hello All,

Facing issues in implementing the Container Image scanning via helm charts.

Out of 5 pods, 3 pods failed with ImagePullbackOff errors, but then worked fine after 10 mins.

  Normal   Scheduled  12m                    default-scheduler  Successfully assigned armo-system/armo-kubescape-67d8bb7fd8-trh4v to minikube
  Warning  Failed     7m50s                  kubelet            Failed to pull image "quay.io/armosec/kubescape:v2.0.156": rpc error: code = Unknown desc = Error response from daemon: Head "https://quay.io/v2/armosec/kubescape/manifests/v2.0.156": Get "https://quay.io/v2/auth?scope=repository%3Aarmosec%2Fkubescape%3Apull&service=quay.io": context deadline exceeded
  Warning  Failed     6m47s (x2 over 7m20s)  kubelet            Failed to pull image "quay.io/armosec/kubescape:v2.0.156": rpc error: code = Unknown desc = Error response from daemon: Get "https://quay.io/v2/": dial tcp: lookup quay.io on 192.168.65.2:53: no such host
  Normal   Pulling    5m52s (x4 over 12m)    kubelet            Pulling image "quay.io/armosec/kubescape:v2.0.156"
  Warning  Failed     5m36s (x4 over 7m50s)  kubelet            Error: ErrImagePull
  Warning  Failed     5m36s                  kubelet            Failed to pull image "quay.io/armosec/kubescape:v2.0.156": rpc error: code = Unknown desc = Error response from daemon: Head "https://quay.io/v2/armosec/kubescape/manifests/v2.0.156": Get "https://quay.io/v2/auth?scope=repository%3Aarmosec%2Fkubescape%3Apull&service=quay.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Normal   BackOff    5m12s (x7 over 7m50s)  kubelet            Back-off pulling image "quay.io/armosec/kubescape:v2.0.156"
  _Warning  Failed     5m12s (x7 over 7m50s)  kubelet            Error: ImagePullBackOff_
  **Normal   Pulled     8s                     kubelet            Successfully pulled image "quay.io/armosec/kubescape:v2.0.156" in 4m2.038971318s**
  
  
  
  Also shown this msg when downloading manually without kubelet downloading it.
  
  
  root@minikube:~# docker pull quay.io/armosec/cluster-collector
Using default tag: latest
Error response from daemon: Get "https://quay.io/v2/": net/http: TLS handshake timeout
root@minikube:~# docker pull quay.io/armosec/cluster-collector:v0.0.1
Error response from daemon: manifest for quay.io/armosec/cluster-collector:v0.0.1 not found: manifest unknown: manifest unknown
root@minikube:~# docker pull quay.io/armosec/cluster-collector:v0.0.1
Error response from daemon: manifest for quay.io/armosec/cluster-collector:v0.0.1 not found: manifest unknown: manifest unknown
root@minikube:~# docker pull quay.io/armosec/cluster-collector

Thanks,
Mustufa M

**Comment by dwertent** [comment]
1. Please make sure your connection to the internet is stable
2. There is no image `quay.io/armosec/cluster-collector:v0.0.1` try -> `quay.io/armosec/cluster-collector:v0.0.12`

**Comment by mustufa5689** [comment]
Hey,

Thanks for the update though.

My internet was already stable and manually pulling it did cause this problem and same was seen when kubelet tried pulling too.

The image was set to pull when kubescape was deployed as a helm charts. I could see the working images on quay.io for rest of the components. My ask is that if higher version is present, kubescape should be made to deploy via helm chart to pull the latest images to avoid such issues.

**Comment by dwertent** [comment]
I'm glad this is working for you, we do not pull the `latest` tag since we do not want uncontrolled image updates.
