### ISSUE TITLE
Why is the clusterName attribute omitted in the scan results json?

### ISSUE THREAD

**Issue by zhujik** [armosec/kubescape#538]
https://github.com/armosec/kubescape/blob/0af0c01ec06975342ff81d71d84f4ce8bc711ffc/core/cautils/customerloader.go#L43

We gather the results in S3 to query them in athena and currently I am running an ETL job on the scan results to insert the clusterName property because it is empty. In the code it is deliberately left out. I wonder why?

**Comment by dwertent** [comment]
The config originally is meant to store the account data, which means the local file cached config is crossed cluster (and not for a single cluster), for that reason we do not store the cluster name there. Notice that the configMap cache (which is in a scope of a cluster) has the cluster name.

Currently, Kubescape will submit the cluster with the context name.
We will add a flag for `cluster-name` so the data can be submitted to a cluster name as you desire. In the meantime, the best way to overcome this obstacle is to edit the `clusterName` in the configMap

**Comment by dwertent** [comment]
Closing since this seems to be resolved
