### ISSUE TITLE
Pods in default namespace control should not fail when namespace is empty

### ISSUE THREAD

**Issue by dwertent** [armosec/kubescape#552]
I'm scanning a local YAML file and I see the control `Pods in default namespace` is failing because I did not specify a namespace in my yaml metadata. 
This should not fail since I'm not actually running the workload at all.

**Comment by danieljkemp** [comment]
It is fairly common to specify the NS at deploy time via `kubectl -n <namespace> apply ...` or `helm --namespace <namespace> ...` In the later case the manifests need to be generated with `helm --dry-run --namespace <namespace> ...`, but in the former there is no option other ignoring the control, or hard-coding the namespace into the manifests....

**Comment by dwertent** [comment]
Based on waht you wrote, the issue is not only in case of this control, but every time kubescape will scan YAMLs from a local directory/git, we cannot pair two resources based on their selector e.g. pods and services. serviceAccounts, roles, and roleBindings.
@slashben  Any thoughts?

**Comment by dwertent** [comment]
Fixed
