### ISSUE TITLE
Make a flag for returning a list of supported framework

### ISSUE THREAD

**Issue by ohadm2** [armosec/kubescape#56]
Hi.

Is there a flag for returning a list of supported frameworks?

I noticed that the docs only refer to "nsa" and I couldn't find a way to make the tool print a full list of frameworks.

Regards,

**Comment by dwertent** [comment]
@ohadm2  Currently Kubescape supports only nsa. We will add more frameworks in the future 😀

**Comment by ohadm2** [comment]
Got it. Thanks.

Btw - amazing job with this tool :)

Keep up the good work!

בתאריך יום א׳, 5 בספט׳ 2021, 17:41, מאת David Wertenteil ‏<
***@***.***>:
