### ISSUE TITLE
Question: SaaS UI self-hosting

### ISSUE THREAD

**Issue by FrittenToni** [armosec/kubescape#578]
Hi,

first of all thanks for developing such a great project. 
I'm not sure if this is the right place to ask a question but since I'm not having Discord I wanted to give it a try. Feel free to close the issue in case it isn't appropriate. 
Now to my question... is it planned to make the SaaS UI available for self hosting? Another user [asked for it](https://github.com/armosec/kubescape/discussions/326) in the discussion section but there hasn't been any reply since January and the upvotes indicate that this is a feature people would love to see :-)

Best Regards,
FrittenToni

**Comment by dwertent** [comment]
Hi @FrittenToni , Thank you for opening this issue and asking your question. Please do not hesitate to open issues and ask questions in the future :)

Yes! we have in our roadmap open-sourcing the portal and all other components. Unfortunately there is a lot of work to be done before we open source the portal so this might take some time.
We will be open-sourcing the [kubescape helm](https://github.com/armosec/armo-helm) microservices source code in the close few weeks 😇

Thanks for linking the question asked in the discussion session, I answered the question there as well so I will close this issue.

**Comment by marcinguy** [comment]
@FrittenToni DM me (email or twitter). I could not find your contact details. I have some UI already, for own purposes.
