### ISSUE TITLE
curl download not recommended way to install tools

### ISSUE THREAD

**Issue by naveensrinivasan** [armosec/kubescape#61]
curl is an insecure pattern for downloading dependencies/tools.

 `curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash `

https://about.codecov.io/security-update/

Why not make a release with GitHub and have instructions to download with gpg signed releases? Also `go install` is another way to install this tool.

**Comment by dwertent** [comment]
Obviously you can directly download the binary or run `go install`, we wanted to provide a one liner installation.
