### ISSUE TITLE
Framework download is broken

### ISSUE THREAD

**Issue by uncycler** [armosec/kubescape#64]
Hello,

kubescape framework download nsa is broken since dashbe.auprod1.cyberarmorsoft.com don't exist.

**Comment by leonidsandler** [comment]
Hi, thank you very much for reporting the problem. It was found and fixed. The new build will go up ASAP. In the meantime you can still use kubescape with scan command, it will download the framework correcly.

**Comment by BenHirschbergCa** [comment]
It was fixed in 1.0.69
