### ISSUE TITLE
Question about JSON results

### ISSUE THREAD

**Issue by victorca25** [armosec/kubescape#66]
Hello! I'm comparing the output from the command and the JSON and while the "Failed Resources" is easy to match to the "ruleResponses" in the JSON for each rule report, I don't seem to find anything in the JSON that can help me define the "All resources" total in order to map it similarly to the tool's "% Success" metric, specially since for each report in "controlReports" this total can vary.

It works fine to get the responses, but I was wondering how could I get that "all resources" value for each report from the JSON. Any tip will help!

**Comment by dwertent** [comment]
@victorca25 We do not print all resources since it might be very heavy.

If you wish to to print them, you can update the [results struct](https://github.com/armosec/kubescape/blob/f60ff1fb26bd334faa775f8ceabbb9698d243ac7/cautils/opapolicy/datastructures.go#L52) ->

From:
```
ListInputResources []map[string]interface{} `json:"-"`
``` 

To:
```
ListInputResources []map[string]interface{} `json:"listInputResources"`
```
