### ISSUE TITLE
How do the newly introduced exceptions work? 

### ISSUE THREAD

**Issue by lftgl** [armosec/kubescape#80]
I have seen the examples, but I do not understand how the `exceptions` work. 
Can some application scenarios please be explained ?

**Comment by BenHirschbergCa** [comment]
hi @lftgl 

We are preparing a full readme and some more perks around this, but here is the idea in general.

You have some Kubernetes objects which are "doomed" to fail always. Example: Kube-proxy will be always (in the current architecture) a privileged container thus will fail the "privileged container" control. Either you want to see those as part of your results/score or not. Exceptions will enable to make this choice: you can say that you don't want to count control "X" on resource "Y" against your results.

Hope it make sense

**Comment by lftgl** [comment]
Ok, i get it, attached is an example exceptions.json that disables all policies for the example resources.
Attention, the actions disabled are written in lower case
```
[
    {
        "name": "ignore-immutable-container-filesystem",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "disable"
        ],
        "resources": [
            {
                "designatorType": "Attributes",
                "attributes": {
                    "kind": "Deployment"
                }
            }
        ],
        "posturePolicies": [
            {
                "frameworkName": "NSA",
                "ruleName": "immutable-container-filesystem"
            },
            {
                "frameworkName": "NSA",
                "ruleName": "linux-hardening"
            },
            {
                "frameworkName": "NSA",
                "ruleName": "ingress-and-egress-blocked"
            }
        ]
    }
]
```

**Comment by good932** [comment]
Dude I don't know who you people think I am but I'm not a programmer or
designer I'm a regular guy who turned on unknown sources on my phone so I
could get paid apps for free then I came across this app and found it very
interesting so I'm just letting you know. I wish most of the stuff I've
already seen on the app I can't figure out but maybe one day I'll get it. I
mean if you really can build something from this app I'd love to build a
powerful SDR Radio

**Comment by dwertent** [comment]
@RothAndrew , @lftgl  I've added a basic documentation and some examples you can find [here](https://github.com/armosec/kubescape/tree/dev/examples/exceptions#kubescape-exceptions) .
