### ISSUE TITLE
Issue with kubescape Installation

### ISSUE THREAD

**Issue by vishalgoyal16444** [armosec/kubescape#87]
Tried installing kubescape on local Jenkins container but there seems to be an issue with installation based on steps mentioned. Similar issue encountered when we tried installing kubescape in our Azure cloud account using Azure shell. (screenshots below)

Please advise on this.

![ab99eef3-34fd-4bb8-b9c7-8de46a25183d](https://user-images.githubusercontent.com/73927117/134156486-0e66cd9e-cfe5-4e03-8b13-346562630992.png)
![231ae186-1e20-4383-8bb4-d2f2fe1b9868](https://user-images.githubusercontent.com/73927117/134156494-3b2b82a6-53a4-4138-8b6c-0e64a3462191.png)

**Comment by good932** [comment]
What the fuck you asking me for I'm not the one who designed it I'm not a
programmer just someone who came across the app found it interesting so I
downloaded it ask someone else.

**Comment by victorca25** [comment]
Had a similar issue on a Docker image, had to explicitly add "apt install sudo" and it worked, but this was not an issue with previous updates

**Comment by BenHirschbergCa** [comment]
Hi @victorca25 @vishalgoyal16444 

We have indeed added `sudo` to the install script (it was needed when a user installed it on a workstation). I will get back to you with a solution!

**Comment by BenHirschbergCa** [comment]
Fixed dependency on `sudo` for installation, please check release 1.0.85
