### ISSUE TITLE
Issue with kubescape installation

### ISSUE THREAD

**Issue by sprathod369** [armosec/kubescape#89]
The issue #87 is marked as fixed and sudo dependencies were supposedly addressed. However, the latest install script still has bugs and is unable to install kubescape. Seems the script bails out midway and not complete the installation cleanly. Please refer the screenshot below.

![image](https://user-images.githubusercontent.com/73107830/134323603-0de7be64-e8e7-4943-a5d6-c58dd5b66539.png)

**Comment by BenHirschbergCa** [comment]
@sprathod369 , you are right, the previous change was not fixing the case when not just `sudo` was missing but you cannot install in `/usr/local/bin` since (like in Azure console) you don't have permissions to write there. Thx for picking this up

Please confirm the latest `install.sh` solves it

**Comment by sprathod369** [comment]
Yes it does address the issue. Screenshot below. Thanks for the support!!

![image](https://user-images.githubusercontent.com/73107830/134620045-83f05ee1-81bc-4f58-b7c2-532922698618.png)
