### ISSUE TITLE
compile release for osx

### ISSUE THREAD

**Issue by bluehawk27** [armosec/kubescape#9]
after running:
`curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash`
ran into the following error:
`: exec format error: kubescape`

**Comment by dwertent** [comment]
Do you still encounter the issue?

**Comment by BenHirschbergCa** [comment]
@bluehawk27 , please re-run with the download script. It should fetch the mac version now

**Comment by bluehawk27** [comment]
It works now, thank you!
