### ISSUE TITLE
Unable to delete a cluster from https://portal.armo.cloud/

### ISSUE THREAD

**Issue by calvinroyston** [armosec/kubescape#94]
Couldn't find an option to delete cluster from https://portal.armo.cloud/ .

**Comment by BenHirschbergCa** [comment]
hi @calvinroyston 

Would you like to delete a specific cluster, or all your data?

**Comment by calvinroyston** [comment]
Hi @BenHirschbergCa ,
The cmd "kubescape scan framework nsa" when used **without** --results-locally=True posts the results to Armo management portal by default . When I log in and check its there but I was unable to find any option to delete that cluster/data recorded . Is there an option to delete a cluster and recorded data ? It would be nice to have that option .

**Comment by BenHirschbergCa** [comment]
Ok, we are on it!

**Comment by dwertent** [comment]
@calvinroyston Fixed :)

1. Navigate to the SaaS version, click on the settings icon on the top right of the page->

  ![image](https://user-images.githubusercontent.com/64066841/141322808-0cb8b4c7-ebe8-4250-988b-d40ebfe215cd.png)

2. Select the cluster you want to delete and press the delete

![image](https://user-images.githubusercontent.com/64066841/141323039-59f620b1-7bf0-4968-a6b3-eac6303e71ec.png)

**Comment by ecarbonell-technisys** [comment]
The Delete option doesn't work.
<img width="392" alt="Screenshot 2022-11-22 at 7 50 51 PM" src="https://user-images.githubusercontent.com/89481127/203437327-ccd73f5d-67ea-48c4-a2a0-efc8896b900d.png">

**Comment by ecarbonell-technisys** [comment]
Reopen the incident pls
