### ISSUE TITLE
404 page not found in About & Readme Link to NSA Hardening Release

### ISSUE THREAD

**Issue by agentpoyo** [armosec/kubescape#97]
In the about for the main repo, the link to nsa.gov takes you to a 404 page not found (also in the main README).

**About**
kubescape is the first tool for testing if Kubernetes is deployed 
securely as defined in Kubernetes Hardening Guidance by to 
NSA and CISA (https://www.nsa.gov/News-Features/Feature-Stories/Article-View/Article/2716980/nsa-cisa-release-kubernetes-hardening-guidance/)

**Comment by taylor** [comment]
Possible alternative link https://www.nsa.gov/Press-Room/News-Highlights/Article/Article/2716980/nsa-cisa-release-kubernetes-hardening-guidance/ found via https://us-cert.cisa.gov/ncas/current-activity/2021/08/02/cisa-and-nsa-release-kubernetes-hardening-guidance

**Comment by dwertent** [comment]
Thanks @taylor
